controller_manager:
  ros__parameters:
    update_rate: 10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:      
      type: velocity_controllers/JointGroupVelocityController

    delivery_box_controller:
      type: position_controllers/JointGroupPositionController



simple_velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_revolute
      - middle_left_wheel_revolute
      - back_left_wheel_revolute
      - front_right_wheel_revolute
      - middle_right_wheel_revolute
      - back_right_wheel_revolute

    command_interfaces:
      - velocity

    state_interfaces:
      - velocity
      - position
    
    pid:
      p: 500.0
      i: 0.1
      d: 5.0

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

delivery_box_controller:
  ros__parameters:
    joints: 
      - del_box_connector
    pid:
      p: 1000.0
      i: 0.1
      d: 10.0

    command_interfaces:
      - position

    state_interfaces:
      - position
    