controller_manager:
  ros__parameters:
    update_rate: 10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_velocity_controller:      
      type: velocity_controllers/JointGroupVelocityController



simple_velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_revolute
      - middle_left_wheel_revolute
      - back_left_wheel_revolute
      - front_right_wheel_revolute
      - middle_right_wheel_revolute
      - back_right_wheel_revolute

    command_interfaces:
      - velocity

    state_interfaces:
      - velocity
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true
