controller_manager:
  ros__parameters:
    update_rate: 100
    

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    simple_position_controller:
      type: position_controllers/JointGroupPositionController

    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    delivery_box_controller:
      type: position_controllers/JointGroupPositionController

simple_position_controller:
  ros__parameters:
    joints:
      - front_left_link_connector_joint
      - front_right_link_connector_joint
      - back_left_link_connector_joint
      - back_right_link_connector_joint

    command_interfaces:
      - position

    state_interfaces:
      - position


simple_velocity_controller:
  ros__parameters:
    joints:
      - front_left_wheel_revolute
      - middle_left_wheel_revolute
      - back_left_wheel_revolute
      - front_right_wheel_revolute
      - middle_right_wheel_revolute
      - back_right_wheel_revolute

    command_interfaces:
      - velocity

    state_interfaces:
      - velocity
      - position
      
      

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

delivery_box_controller:
  ros__parameters:
    joints:
      - del_box_connector
      

    command_interfaces:
      - position

    state_interfaces:
      - position
